baseURL = "https://note.goharry.dev"
title = "Harry's Note"
theme = "paper"
enableGitInfo = true
enableRobotsTXT = true
DefaultContentLanguage = "zh"
[permalinks]
  posts = "/:year/:month/:filename/"
  pages = "/:filename/"
[params]
  repo = "https://github.com/housne/note"
  description = "Harry 的日常笔记"
[languages]
  [languages.zh]
    languageName = "中文"
    languageCode = "zh-cn"
    title = "Harry 的笔记"
    hasCJKLanguage = true
    weight = 0
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    title = "Harry's Note"
    weight = 1


