baseURL: https://note.goharry.dev
title: Harry
theme: paper
enableGitInfo: true
enableRobotsTXT: true
DefaultContentLanguage: zh
Paginate: 5

permalinks:
  posts: /:year/:month/:filename/
  pages: /:filename/
  running: /running/:year/:month/:day/

params:
  repo: https://github.com/housne/note
  description: Harry 的日常笔记
  staticmanURL: https://comment-goharry.herokuapp.com/v2/entry/housne/note/master/comments
  images:
    maxWidth: 688
  
 
  

languages:
  zh:
    languageName: 中文
    languageCode: zh-cn
    hasCJKLanguage: true
    weight: 0
  en:
    languageName: English
    languageCode: en-us
    weight: 1



